config/routes.rb
Blog::Application.routes.draw do
  resources :projects

  resources :images

  devise_for :users
  post "select_theme", to: "welcome#select_theme", as: "select_theme"
  get "images", to: "images", as: "image_upload"
  get "projects", to: "projects", as: "project_upload"
  get "admin/page_one", to: "admin#page_one"
  get "admin/restricted", to: "admin#restricted", as: 'restricted'
  get "admin/page_two", to: "admin#page_two"
  get "gallery", to: "gallery#index", as: 'gallery'
  get "news", to: "news#index", as: 'news'
  get "resume", to: "resume#index", as: 'resume'
  get "portfolio", to: "portfolio#index", as: 'portfolio'
  root "welcome#index"
  get "sitemap", to: "sitemap#index", as: 'sitemap'
  get "aboutme", to: "aboutme#index", as: 'aboutme'
  get "welcome", to: "welcome#index", as: 'welcome'
  post 'say_hi', to: 'welcome#say_hi'
  get "gallery/secret", to: "gallery#secret", as: "secret"

  

end

app/models/image.rb
class Image < ActiveRecord::Base
	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png",
	:storage => :s3,
    :bucket => 'blog1245',
    :s3_credentials => {
      :access_key_id => 'AKIAIAZF5Q3QKJAZVPHQ',
      :secret_access_key => '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'
    }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/theme.rb
class Theme < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_one :theme
end

app/controllers/aboutme_controller.rb
class AboutmeController < ApplicationController
  def index
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin_user
  def page_one
  end

  def page_two
  end

  def admin_user
    if current_user.admin != true
      redirect_to(welcome_path, alert:"You're not an admin")
    end
  end
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  def index
  	# @image_names = ['IMG_01','IMG_02','IMG_03','IMG_04']
  	@images = Image.all # [image_records]
  end

  def secret
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin_user
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  # GET /images
  # GET /images.json
  def admin_user
    if current_user.admin != true
      redirect_to(welcome_path, alert:"You're not an admin")
    end
  end
  
  def index
    @images = Image.all
  end

  # GET /images/1
  # GET /images/1.json
  def show
  end

  # GET /images/new
  def new
    @image = Image.new
  end

  # GET /images/1/edit
  def edit
  end

  # POST /images
  # POST /images.json
  def create
    @image = Image.new(image_params)

    respond_to do |format|
      if @image.save
        format.html { redirect_to @image, notice: 'Image was successfully created.' }
        format.json { render action: 'show', status: :created, location: @image }
      else
        format.html { render action: 'new' }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /images/1
  # PATCH/PUT /images/1.json
  def update
    respond_to do |format|
      if @image.update(image_params)
        format.html { redirect_to @image, notice: 'Image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /images/1
  # DELETE /images/1.json
  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_image
      @image = Image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def image_params
      params.require(:image).permit(:name, :description, :file_name, :image)
    end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
  end
end

app/controllers/resume_controller.rb
class ResumeController < ApplicationController
  def index
  end
end

app/controllers/sitemap_controller.rb
class SitemapController < ApplicationController
  def index
  end
end

app/helpers/aboutme_helper.rb
module AboutmeHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/helpers/sitemap_helper.rb
module SitemapHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/aboutme/dogs.html.erb
Dogs

app/views/aboutme/index.html.erb
<head>
</head>
<body>
<h1 class="center">About me</h1>
<center><img src="/assets/IMG_04.jpg" alt="Wembley Fraggle"></center>
<p class="center">In lieu of my photo, here is my spirit animal</p>

<ul>
	<li>My name is Aaron.</li>
	<li>This is a list.</li>
	<li>I'm not good at self promotion</li>
</ul>	
</body>

app/views/gallery/index.html.erb
<h1>Gallery#index</h1>
<p>Find me in app/views/gallery/index.html.erb</p>


<ul>
	<% @images.each do |image_record|%>
	  <center><li class="gallery"><%= image_tag(image_record.file_name) %></li>
	  <p>Name: <%= image_record.name %></p>
	  <p>Description: <%= image_record.description%></p></center>
	<% end %>
</ul>
<style>
	img {width: 20%;
		}
</style>

app/views/gallery/secret.html.erb
<iframe width="560" height="315" src="//www.youtube.com/embed/XcHAebR9Aa8" frameborder="0" allowfullscreen></iframe>

app/views/news/index.html.erb
<h1>News</h1>

<p>Print is dead, why are you checking this?</p>

app/views/resume/index.html.erb
<h1>Resume</h1>
<p><a href=https://github.com/masteraero>Github Profile</a></p>
<p><a href=www.linkedin.com/pub/aaron-nealey/34/393/b1/>Linkedin</a></p>

app/views/sitemap/index.html.erb
<body>
<center><h1>Site Map</h1><center>

<div class="left">
	<p><%= link_to "aboutme" , aboutme_path %></p>
	<p><%= link_to "welcome" , welcome_path %></p>
	<p><%= link_to "portfolio" , portfolio_path %></p>
	<p><%= link_to "resume" , resume_path %></p>
	<p><%= link_to "news" , news_path %></p>
	<p><%= link_to "gallery", gallery_path%></p>
</div>
</body